### ISSUE TITLE
Need moar context on new files

### ISSUE THREAD

**Issue by progers** [esprehn/chromium-codereview#12]
If you add a new file (such as LayoutTests/fast/text-autosizing/display-type-change.html in https://codereview.chromium.org/app/#/issue/315873002) only a few lines of the new file are shown. This makes it hard to review new files.

![context](https://cloud.githubusercontent.com/assets/569214/3210125/a04c3f6a-eea4-11e3-9a6f-858459bb18dc.png)

**Comment by esprehn** [comment]
What version of Chrome are you on? I see the whole file over here.

**Comment by progers** [comment]
36.0.1985.49 beta, experimental web platform features are enabled. In the inspector I only see the three lines shown in the screenshot so the extra lines aren't hiding under something.

**Comment by esprehn** [comment]
Interesting, I'll see if I can reproduce. Perhaps it's some kind of error when syntax highlighting or parsing the diff. 37.0.2017.2 dev works, can you try it?

**Comment by progers** [comment]
Still repros for me at 37.0.2024.3 dev. I don't want to send you on a wild ~~goose~~ line chase.. lets compare our chromes on Monday.

**Comment by ojanvafai** [comment]
I also don't get context on that patch on

Google Chrome   37.0.2024.3 (Official Build 274925) dev
OS  Mac OS X 
Blink   537.36 (@175221)

**Comment by chrishtr** [comment]
Same here for:

https://codereview.chromium.org/328533003 (layout test only shows the first 12 lines).

**Comment by esprehn** [comment]
Can you open the web inspector and choose "Sources", click the stop sign, and then tell me what the error is? I can't reproduce this.

**Comment by esprehn** [comment]
Woops, mentioned the wrong issue in that commit. That was for issue #24.

**Comment by jchaffraix** [comment]
Seen this issue on 0.10 on https://codereview.chromium.org/204843002, check the diff for LayoutTests/fast/repaint/change-height-width.html with the extension and without (https://codereview.chromium.org/204843002/patch/80001/90012).

Here is the trace I have:

Exception caught during observer callback: TypeError: undefined is not a function
    at PatchFile.selectEmbeddedLanguage (chrome-extension://cejmlbfbgonembodpobaeigfdnplpnff/ui/model/patch_file.js:82:45)
    at chrome-extension://cejmlbfbgonembodpobaeigfdnplpnff/ui/components/cr-diff.html/cr-diff.js:136:45
    at Array.forEach (native)
    at chrome-extension://cejmlbfbgonembodpobaeigfdnplpnff/ui/components/cr-diff.html/cr-diff.js:129:27
    at Array.forEach (native)
    at cr-diff.Polymer.createDiff (chrome-extension://cejmlbfbgonembodpobaeigfdnplpnff/ui/components/cr-diff.html/cr-diff.js:125:34)
    at cr-diff.Polymer.activeChanged (chrome-extension://cejmlbfbgonembodpobaeigfdnplpnff/ui/components/cr-diff.html/cr-diff.js:94:26)
    at cr-diff.e.invokeMethod (chrome-extension://cejmlbfbgonembodpobaeigfdnplpnff/bower_components/polymer/polymer.js:12:10242)
    at cr-diff.e.notifyPropertyChanges (chrome-extension://cejmlbfbgonembodpobaeigfdnplpnff/bower_components/polymer/polymer.js:12:9459)
    at Object.Observer.report_ (chrome-extension://cejmlbfbgonembodpobaeigfdnplpnff/bower_components/platform/platform.js:12:12892)
    at Object.createObject.check_ (chrome-extension://cejmlbfbgonembodpobaeigfdnplpnff/bower_components/platform/platform.js:12:18381)
